;; Solution to Project Euler problem 2
;; http://projecteuler.net/index.php?section=problems&id=2
;;
;; Each new term in the Fibonacci sequence is generated by adding
;; the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.
(ns com.stepniowski.euler-002)

(defn fibonacci-numbers
  ([]
     (concat [1 2] (fibonacci-numbers 1 2)))
  ([a b]
     (let [n (+ a b)]
       (lazy-seq
	(cons n (fibonacci-numbers b n))))))

(defn solution []
  (let [fibs (take-while #(< % 4000000)
			 (fibonacci-numbers))]
    (reduce + (filter even? fibs))))
